### ISSUE TITLE
This repository is empty.

### ISSUE THREAD

**Issue by Foxcapades** [cagedit/javascript-neural-network#1]
That's my issue.

**Comment by Foxcapades** [comment]
Issue resolved.

**Comment by cage-is** [comment]
@Foxcapades Are you okay?

**Comment by Foxcapades** [comment]
@cage-is are _you_ okay? Is _anyone_ okay?  These questions are far too big for a javascript neural network.

**Comment by cagedit** [comment]
Zomg you’re alive! I’ve been trying to talk to you for months on every
platform I know. If you don’t want to talk to me, I’ll accept it if you say
so but otherwise I’m gonna keep spamming you with messages :-B

**Comment by Foxcapades** [comment]
I _am_ alive!  And pls keep sending spam, I haven't seen it yet but my frying pan is already ready!

I kinda stopped using skype, 'cause it's for nubs, but also because I went a while without windows and just sorta forgot it existed.  If u r use discord I am also use that, but also I have randomly decided to be on facebook again.  Additionally I will turn on skype if I can remember my login deets...  also for slack...

**Comment by Foxcapades** [comment]
Also when you hover over my icon it says "PRO" i have no idea what that means since it is absolutely false, but I love it anyway

**Comment by cage-is** [comment]
Installed discord but don't know what I am doing because am nub

**Comment by Foxcapades** [comment]
add frond `EHarper#8317`

that's probably me, i think
